export const audioMap = {
  "Welcome to Division as Grouping!": "/assets/audio/audio_welcome_to_division_as_grouping__0.mp3",
  "Today, we're going to learn how to split numbers into equal groups.": "/assets/audio/audio_today__we_re_going_to_learn_how_to_split_numbers_i_1.mp3",
  "If I have 12 apples and want 4 in each basket, how many baskets do I need?": "/assets/audio/audio_if_i_have_12_apples_and_want_4_in_each_basket__how_4.mp3",
  "Are you ready to join Leo on a fun grouping adventure? Let's begin our learning journey!": "/assets/audio/audio_are_you_ready_to_join_leo_on_a_fun_grouping_advent_3.mp3",
  "Division is about making equal groups — let us find out!": "/assets/audio/audio_division_is_about_making_equal_groups___let_us_fin_5.mp3",
  "If there are 20 stickers and we put 5 in each bag, how many bags can we make?": "/assets/audio/audio_if_there_are_20_stickers_and_we_put_5_in_each_bag__6.mp3",
  "When we group equally, we are dividing!": "/assets/audio/audio_when_we_group_equally__we_are_dividing__7.mp3",
  "How can equal grouping help us solve division?": "/assets/audio/audio_how_can_equal_grouping_help_us_solve_division__8.mp3",
  "Groups are like teams — same size, counted together!": "/assets/audio/audio_groups_are_like_teams___same_size__counted_togethe_9.mp3",
  "If 3 times 4 equals 12, what is 12 divided by 3?": "/assets/audio/audio_if_3_times_4_equals_12__what_is_12_divided_by_3__10.mp3",
  "Multiplication and division are best friends!": "/assets/audio/audio_multiplication_and_division_are_best_friends__11.mp3",
  "What happens when we split a big number into equal smaller groups?": "/assets/audio/audio_what_happens_when_we_split_a_big_number_into_equal_12.mp3",
  "That is exactly what division as grouping does!": "/assets/audio/audio_that_is_exactly_what_division_as_grouping_does__13.mp3",
  "Leo picked 12 shiny apples from his garden. He wants to pack them into baskets with 3 apples in each basket. Leo wonders...": "/assets/audio/audio_leo_picked_12_shiny_apples_from_his_garden__he_wan_14.mp3",
  "How many baskets do I need?": "/assets/audio/audio_how_many_baskets_do_i_need__15.mp3",
  "Let's help Leo group his apples!": "/assets/audio/audio_let_s_help_leo_group_his_apples__16.mp3",
  "To find out, we make equal groups. We put 3 apples in each basket until all 12 apples are packed. This is called division as grouping!": "/assets/audio/audio_to_find_out__we_make_equal_groups__we_put_3_apples_17.mp3",
  "12 divided by 3 equals 4 baskets!": "/assets/audio/audio_12_divided_by_3_equals_4_baskets__18.mp3",
  "Division means making equal groups!": "/assets/audio/audio_division_means_making_equal_groups__19.mp3",
  "Leo drew circles to show his groups. Each circle is one basket with 3 apples inside. He counted the circles and found 4 groups. \"When I know the group size, I count how many groups I can make!\" he said.": "/assets/audio/audio_leo_drew_circles_to_show_his_groups__each_circle_i_20.mp3",
  "Group size times number of groups equals the total!": "/assets/audio/audio_group_size_times_number_of_groups_equals_the_total_21.mp3",
  "Count the groups to solve!": "/assets/audio/audio_count_the_groups_to_solve__22.mp3",
  "Leo was so excited! He learned that division is the opposite of multiplication. \"Can we practice more grouping?\" he asked Emma.": "/assets/audio/audio_leo_was_so_excited__he_learned_that_division_is_th_23.mp3",
  "Equal groups — here we come!": "/assets/audio/audio_equal_groups___here_we_come__24.mp3",
  "Your turn now!": "/assets/audio/audio_your_turn_now__25.mp3",
  "Drag 12 objects into groups of 3. Count how many groups you make!": "/assets/audio/audio_drag_12_objects_into_groups_of_3__count_how_many_g_26.mp3",
  "Drag 8 objects into groups of 2. Count how many groups you make!": "/assets/audio/audio_drag_8_objects_into_groups_of_2__count_how_many_gr_27.mp3",
  "Drag 15 objects into groups of 5. Count how many groups you make!": "/assets/audio/audio_drag_15_objects_into_groups_of_5__count_how_many_g_28.mp3",
  "Drag 16 objects into groups of 4. Count how many groups you make!": "/assets/audio/audio_drag_16_objects_into_groups_of_4__count_how_many_g_29.mp3",
  "Tap to circle equal groups of dots on the grid. How many groups can you make?": "/assets/audio/audio_tap_to_circle_equal_groups_of_dots_on_the_grid__ho_30.mp3",
  "Jump along the number line in equal steps. Each jump is one group!": "/assets/audio/audio_jump_along_the_number_line_in_equal_steps__each_ju_31.mp3",
  "Fill in the division sentence! Use the number pad.": "/assets/audio/audio_fill_in_the_division_sentence__use_the_number_pad__32.mp3",
  "12 divided by 3 equals 4 groups!": "/assets/audio/audio_12_divided_by_3_equals_4_groups__33.mp3",
  "Great grouping!": "/assets/audio/audio_great_grouping__34.mp3",
  "8 divided by 2 equals 4 groups!": "/assets/audio/audio_8_divided_by_2_equals_4_groups__35.mp3",
  "15 divided by 5 equals 3 groups!": "/assets/audio/audio_15_divided_by_5_equals_3_groups__36.mp3",
  "16 divided by 4 equals 4 groups!": "/assets/audio/audio_16_divided_by_4_equals_4_groups__37.mp3",
  "3 jumps of 4 make 12!": "/assets/audio/audio_3_jumps_of_4_make_12__38.mp3",
  "Yes! 12 divided by 3 equals 4!": "/assets/audio/audio_yes__12_divided_by_3_equals_4__39.mp3",
  "Yes! 8 divided by 4 equals 2!": "/assets/audio/audio_yes__8_divided_by_4_equals_2__40.mp3",
  "What did you learn about division as grouping?": "/assets/audio/audio_what_did_you_learn_about_division_as_grouping__41.mp3",
  "How confident do you feel about dividing into equal groups?": "/assets/audio/audio_how_confident_do_you_feel_about_dividing_into_equa_42.mp3",
  "Welcome to Apple Orchard!": "/assets/audio/audio_welcome_to_apple_orchard__43.mp3",
  "Welcome to Sticker Studio!": "/assets/audio/audio_welcome_to_sticker_studio__44.mp3",
  "Welcome to Toy Town!": "/assets/audio/audio_welcome_to_toy_town__45.mp3",
  "Welcome to Puppy Park!": "/assets/audio/audio_welcome_to_puppy_park__46.mp3",
  "Welcome to Pencil Palace!": "/assets/audio/audio_welcome_to_pencil_palace__47.mp3",
  "Welcome to Group Galaxy!": "/assets/audio/audio_welcome_to_group_galaxy__48.mp3",
  "Welcome to Basket Bay!": "/assets/audio/audio_welcome_to_basket_bay__49.mp3",
  "Welcome to Number Nest!": "/assets/audio/audio_welcome_to_number_nest__50.mp3",
  "Welcome to Rainbow Groups!": "/assets/audio/audio_welcome_to_rainbow_groups__51.mp3",
  "Welcome to Division Castle!": "/assets/audio/audio_welcome_to_division_castle__52.mp3",
  "Apple Orchard Complete!": "/assets/audio/audio_apple_orchard_complete__53.mp3",
  "Score: 8 out of 10": "/assets/audio/audio_score__8_out_of_10_54.mp3"
};
